lighttpd: peg at 1.4.55
newer version not building due to
ls-hpack/lshpack.c: In function 'lshpack_enc_huff_encode':
ls-hpack/lshpack.c:703: error: #pragma GCC diagnostic not allowed inside
functions

at least